apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping-app-deployment
  labels:
    app: ping-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ping-app-deployment
  template:
    metadata:
      labels:
        app: ping-app-deployment
    spec:
      containers:
      - name: ping-api
        image: docker.io/k8s/ping-api:0.0.2
        ports:
        - containerPort: 9000
