apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: thirdnginx
  name: thirdnginx
spec:
  containers:
  - image: nginx
    name: thirdnginx
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
